# Generated by Django 2.2.16 on 2021-12-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0006_auto_20211201_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eng_yaxshi',
        ),
        migrations.AddField(
            model_name='talabalar',
            name='eng_yaxshi',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loyiha',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='talabalar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
